---
- hosts: newcdn
  tasks:
    - name: "GENERATE KEY"
      user:
        name: "root"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: "~/.ssh/id_rsa"
      register: keyfile
    - debug: var=keyfile

